"""Fix track created type

Revision ID: 5d12d7f0c0f2
Revises: 6283d402f38d
Create Date: 2021-07-19 23:15:39.569439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d12d7f0c0f2'
down_revision = '6283d402f38d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracks', 'created',
        type_=sa.TIMESTAMP(),
        nullable=True,
        postgresql_using='to_timestamp(created) AT TIME ZONE \'UTC\'')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracks', 'created',
        type_=sa.Integer(),
        nullable=True)
    pass
    # ### end Alembic commands ###
